env:
  - DB=postgres
  - DATABASE_URL=postgres://admin:doggo@localhost:5432/dogspotting
  - DATABASE_TEST_URL=postgres://admin:doggo@localhost:5432/dogspotting_test

language: node_js
node_js :
 - "node"
after_success: npm run coverage

before_script:
  - psql -c "CREATE DATABASE dogspotting;" -U postgres
  - psql -c "CREATE DATABASE dogspotting_test;"
  - psql -c "CREATE USER admin WITH PASSWORD 'doggo';" -U postgres
  - psql -c "ALTER DATABASE dogspotting OWNER TO admin;" -U postgres
  - psql -c "ALTER DATABASE dogspotting_test OWNER to admin;" -U postgres